language: r
sudo: false
cache: packages

r_packages:
 - devtools

warnings_are_errors: true

notifications:
  email:
    on_success: change
    on_failure: always

# only use travis on master branch
branches:
  only:
  - master

# avoid timeout (see <https://github.com/travis-ci/travis-ci/issues/3849#issuecomment-255096774>)
script:
  - |
    R CMD build .
    travis_wait 20 R CMD check --as-cran qtl2_*.tar.gz

# print install log
after_failure:
 - cat qtl2.Rcheck/00install.out

after_success:
 - cat qtl2.Rcheck/00install.out
